# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FdUkfQCBvEWRD7R0SSOvcX_3XsYbpU9
"""

# ============================================
# 🐄 DairySense AI - Google Colab Full Code
# Milk Yield Prediction + Health Risk Detection
# ============================================

# =========================
# STEP 1: IMPORT LIBRARIES
# =========================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

import matplotlib.pyplot as plt

# =========================
# STEP 2: LOAD DATASET
# =========================

# Upload CSV in Colab first
# Example file name: dairy_dataset.csv

df = pd.read_csv("dairy_dataset.csv")

# =========================
# STEP 3: VIEW DATA
# =========================

print(df.head())

print("\nDataset Shape:")
print(df.shape)

# =========================
# STEP 4: CLEAN COLUMN NAMES
# =========================

df.columns = df.columns.str.strip().str.lower()

print("\nColumns:")
print(df.columns)

# =========================
# STEP 5: ENCODE TEXT DATA
# =========================

encoder = LabelEncoder()

categorical_cols = [
    'breed',
    'lactation_stage',
    'feed_quality',
    'activity_level',
    'appetite',
    'health_status'
]

for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

# =========================
# STEP 6: FEATURES & TARGETS
# =========================

X = df.drop(["milk_yield", "health_status"], axis=1)

y_milk = df["milk_yield"]

y_health = df["health_status"]

# =========================
# STEP 7: TRAIN TEST SPLIT
# =========================

X_train, X_test, y_milk_train, y_milk_test = train_test_split(
    X,
    y_milk,
    test_size=0.2,
    random_state=42
)

X_train2, X_test2, y_health_train, y_health_test = train_test_split(
    X,
    y_health,
    test_size=0.2,
    random_state=42
)

# =========================
# STEP 8: TRAIN MODELS
# =========================

# Milk Prediction Model
milk_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

milk_model.fit(X_train, y_milk_train)

# Health Prediction Model
health_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

health_model.fit(X_train2, y_health_train)

# =========================
# STEP 9: PREDICTIONS
# =========================

milk_pred = milk_model.predict(X_test)

health_pred = health_model.predict(X_test2)

# =========================
# STEP 10: EVALUATION
# =========================

milk_mae = mean_absolute_error(
    y_milk_test,
    milk_pred
)

health_acc = accuracy_score(
    y_health_test,
    health_pred
)

print("\n============================")
print("🐄 DairySense AI Results")
print("============================")

print(f"\nMilk Prediction MAE: {milk_mae:.2f}")

print(f"\nHealth Prediction Accuracy: {health_acc:.2f}")

# =========================
# STEP 11: SAMPLE PREDICTION
# =========================

sample = X.iloc[[0]]

milk_value = milk_model.predict(sample)[0]

health_value = health_model.predict(sample)[0]

print("\n============================")
print("🔍 Sample Prediction")
print("============================")

print(f"\n🥛 Predicted Milk Yield: {milk_value:.2f} Litres/day")

if health_value == 0:
    print("🩺 Health Status: Healthy ✅")
else:
    print("🩺 Health Status: At Risk ⚠️")

# =========================
# STEP 12: VISUALIZATION
# =========================

# Milk Prediction Chart

plt.figure(figsize=(5,5))

plt.bar(
    ["Milk Yield"],
    [milk_value]
)

plt.title("Milk Yield Prediction")

plt.ylabel("Litres")

plt.show()

# =========================
# STEP 13: HEALTH CHART
# =========================

labels = ["Healthy", "At Risk"]

values = [1, 0] if health_value == 0 else [0, 1]

plt.figure(figsize=(5,5))

plt.bar(labels, values)

plt.title("Health Risk Prediction")

plt.show()

# =========================
# STEP 14: FEATURE IMPORTANCE
# =========================

importance = milk_model.feature_importances_

feature_names = X.columns

plt.figure(figsize=(10,5))

plt.bar(feature_names, importance)

plt.xticks(rotation=45)

plt.title("Feature Importance for Milk Prediction")

plt.show()

# =========================
# STEP 15: SAVE MODELS
# =========================

import joblib

joblib.dump(milk_model, "milk_model.pkl")

joblib.dump(health_model, "health_model.pkl")

print("\n✅ Models Saved Successfully")